"""add hero_sr_updates table

Revision ID: d11c7c62595c
Revises: b1c2d3e4f5a6
Create Date: 2026-04-09 04:59:39.470913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11c7c62595c'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_sr_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rank_update_id', sa.Uuid(), nullable=False),
    sa.Column('hero', sa.String(), nullable=False),
    sa.Column('sr', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rank_update_id'], ['rank_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_sr_updates')
    # ### end Alembic commands ###
