"""initial schema

Revision ID: e34ff37c1c19
Revises: 
Create Date: 2026-02-28 02:15:55.279858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34ff37c1c19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('queue_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('eliminations', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.Column('mitigation', sa.Integer(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_stat_id', sa.Uuid(), nullable=False),
    sa.Column('hero_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('hero_stat_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hero_stat_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hero_stat_id'], ['hero_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_stat_values')
    op.drop_table('hero_stats')
    op.drop_table('player_stats')
    op.drop_table('matches')
    # ### end Alembic commands ###
